name: TCS
version: ${project.version}
main: me.jurre.tcs.Tcs
api-version: 1.16
authors: [Jurre]
description: Unofficial TCS Minecraft plugin
website: https://www.jurre.me/
commands:
  donator:
    description: "set donators"
    usage: /donator
  nickname:
    description: "change nickname"
    usage: /nickname
  discord:
    description: "server invite link"
    usage: /discord
  map:
    description: "dynmap link"
    usage: /map